import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer'; // Import Footer
import { NextAuthProvider } from "./components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`} suppressHydrationWarning>
        <NextAuthProvider>
          <Navbar />
          <main className="flex-grow w-full mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-8">
            {children}
          </main>
          {modal}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
